#include <iostream>
#include <string>
#include <iomanip>
#include <cstdlib>
#include <ctime>
#include "graphicFcts.h"

using namespace std;

const int row = 20;
const int col = 20;
string room[col][row];

int currentRow = 1;
int currentCol = 1;

string movInput = "X";
string movement = "X";

int randomTrapGeneratorRow;
int randomTrapGeneratorCol;
int randomMonsterGeneratorRow;
int randomMonsterGeneratorCol;

int gogglesRow;
int gogglesCol;
int potionRow;
int potionCol;
int hammerCol;
int hammerRow;

bool gogglesFound = false;
bool potionFound = false;
bool hammerFound = false;

bool trapDetector = false;


bool gameWon = false;
bool validMove = true;
bool startOfGame = true;



bool hitTrap = false;
bool hitMonster = false;

int changeTraps = 0;

int healthPoints = 100;



void printInstructions(){
    
    string input;
    
    cout << setw(300) << "D U N G E O N  M A S T E R \n" << endl;
    cout << "\nWelcome to Dungeon Master. Your goal is to reach the bottom right corner to escape the dungeon. \n" << endl;
    cout << "If you meet a trap, you will have 3 chances to find the random number from 0 to 9 generated by the dungeon." << endl;
    cout << "If you meet a monster, you'll have to play a rock-paper-scissors game. " << endl;
    
    cout << "If you lose the trap challenge, you'll be docked 10HP. If you lose against the monster, you'll be docked 30HP. You start with 100HP." << endl;
    
    cout << "\nThe Master is playful. He changes the trap positions often and monsters move fast. Take that into consideration." << endl;
    
    cout << "\nThis is your character: ᗤ \n" << endl;
    
    cout << "You might encouter different items during the game: " << endl;
    cout << "\t♥ - The Potion of Ressurection. If you die, it will ressurect you with 10 HP." << endl;
    cout << "\t⎌ - The Master's Goggles. If you are close to encountering a trap or monster, it will signal you with the following symbol: ⚠︎. They only work for a limited amount of time however. " << endl;
    cout << "\t⚒︎ - The Thunder Hammer. You get an extra chance every time you face a monster." << endl;
    
    cout << "\nPress any key when you're ready to start" << endl;
    cin >> input;
    drawRoom();
    // cout << "\n \n \n" << endl;
    
    
}

void drawRoom(){
    
    for (int i=0; i<row; i++){
        for (int j=0; j<col; j++){
            
            if(i == currentRow && j == currentCol){
                
                if (movement == "A") {
                    room[i][j] = "ᗤ";
                }
                
                else if(movement == "S"){
                    room[i][j] = "ᗣ";
                    if(i == row - 2 && j == col - 2){
                        gameWon = true;
                    }
                }
                
                else if(movement == "W"){
                    room[i][j] = "ᗢ";
                }
                
                else{
                    room[i][j] = "ᗧ";
                }
                
                if(i == row - 2 && j == col - 2){
                    gameWon = true;
                }
                
            }
            
            
            else if(i == 0){
                room [i][j] = "-";
            }
            else if(j == col-1 && i < row - 2){
                room[i][j] = "|";
            }
            else if(i == row-1){
                room[i][j] = "-";
            }
            else if(j == 0){
                room[i][j] = "|";
            }
            else{
                room[i][j] = ".";
            }
 
            
            cout << room[i][j];
            
            if(j == col-1){
                if(i==1){
                    cout << "\t \t \t \t  HP: " << healthPoints;
                }
                
                if(gogglesFound == true){
                    if(i == 2){
                        cout << "\t \t \t \t  ITEM: ⎌";
                    }
                }
                
                if(potionFound == true){
                    if (i == 3){
                        cout << "\t \t \t \t  ITEM: ♥";
                    }
                }
                
                if(hammerFound == true){
                    if(i == 4){
                        cout << "\t \t \t \t  ITEM: ⚒︎";
                    }
                }
                
                
                if(hitTrap == true){
                    if(i == 10){
                        cout << "\t \tTrap! Guess the number in 0-9.";
                    }
                }
                
                else if(hitMonster == true){
                    if(i == 10){
                        cout << "\t \tMonster! Rock (1), paper (2) or scissors (3)?";
                    }
                }
                
            }
            
            if(gameWon == true){
                cout << "\n\nGAME WON!" << endl;
                exit(0);
            }
            
            
        }
        cout << "\n";
    }
    
    if(hitTrap == true){
        trapAction();
        cin.clear(); // reset failbit
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); //skip bad input
        // next, request user reinput
        cin.sync();
    }
    
    if(hitMonster == true){
        monsterAction();
    }
    
    
    
}


void drawPlayer(){
    
    if(startOfGame == true){
        currentRow = 1;
        currentCol = 1;
        startOfGame = false;
    }
    
    if(healthPoints <= 0){
        if(potionFound == false){
            cout << "YOU DIED" << endl;
            exit(0);
        }
        else if(potionFound == true){
            potion();
            potionFound = false;
        }
    }
    else{
        cin.sync();
        cin >> movInput;
        cin.ignore();
        
        movement = movInput.substr(0, 1);
        
        
        //In this blocks, I use validMove to confirm the call of drawRoom().
        //If the player is trying to get out of the borders, validMove is set to false and we replace the player to its initial position before the move.
        //I am conscious that deleting the validMove part as such would work too: (e.g.: movement = S)
        /* if(currentRow > row - 1){
         currentRow = currentRow - 1;
         }
         */
        //However, it would still call drawRoom() even if it doesn't display the move. drawRoom() is a fct running in O(n^2) and for efficiency purposes, it's better to check if we can avoid calling it.
        
        if(movement == "S"){
            currentRow = currentRow + 1;
            if(currentRow < row - 1){
                validMove = true;
            }
            else{
                validMove = false;
                currentRow = currentRow - 1;
            }
        }
        else if(movement == "W"){
            currentRow = currentRow - 1;
            if(currentRow > 0){
                validMove = true;
            }
            else{
                validMove = false;
                currentRow = currentRow + 1;
            }
        }
        else if(movement == "D"){
            currentCol = currentCol + 1;
            if(currentCol < col - 1){
                validMove = true;
            }
            else{
                validMove = false;
                currentCol = currentCol - 1;
            }
        }
        else if(movement == "A"){
            currentCol = currentCol - 1;
            if(currentCol > 0){
                validMove = true;
            }
            else{
                validMove = false;
                currentCol = currentCol +1;
            }
        }
        
    }
    
    room[currentCol][currentRow] = "ᗤ";
    
    if(validMove == true){
        drawRoom();
    }
    
}


void checkTrap(){
    
    srand(time(NULL));
    
    hitMonster = false;
    hitTrap = false;
    changeTraps = 0;
    
    if(changeTraps % 4 == 0 || hitMonster == true || hitTrap == true || startOfGame == true){
        
        //Print position of current trap.
        randomTrapGeneratorRow = rand() % (row/4) + 1;
        randomTrapGeneratorCol = rand() % (col/4) + 1;
        randomMonsterGeneratorRow = rand() % (row/4) + 1;
        randomMonsterGeneratorCol = rand() % (col/4) + 1;
    }
//
//    cout << "TRAP: R = " << randomTrapGeneratorRow << " C = " << randomTrapGeneratorCol << endl;
//    cout << "MONSTER: R = " << randomMonsterGeneratorRow << " C = " << randomMonsterGeneratorCol << endl;
//    cout << "CURRENT: R = " << currentRow << " C = " << currentCol << endl;
    
    if(currentRow % randomMonsterGeneratorRow == 0 && currentCol % randomMonsterGeneratorCol == 0){
        hitMonster = true;
    }
    else if (currentRow % randomTrapGeneratorRow == 0 && currentCol % randomTrapGeneratorCol == 0){
        hitTrap = true;
    }
        
   
    
    

    changeTraps++;
    
}

void checkItem(){
    
    if(currentRow == gogglesRow && currentCol == gogglesCol){
        gogglesFound = true;
    }
    else if(currentRow == potionRow && currentCol == gogglesCol){
        potionFound = true;
    }
    else if(currentRow == hammerRow && currentCol == hammerCol){
        hammerFound = true;
    }
    
}

void generateItems(){
    
    //    gogglesRow = rand() % row + 1;
    //    gogglesCol = rand() % col + 1;
    //    potionRow = rand() % row + 1;
    //    potionCol = rand() % col + 1;
    //    hammerRow = rand() % row + 1;
    //    hammerCol = rand() % col + 1;
    
    gogglesRow = 2;
    gogglesCol = 2;
    potionRow = 3;
    potionCol = 3;
    hammerRow = 4;
    hammerCol = 4;
    
}

void goggles(){
    
}
void potion(){
    if(potionFound == true && healthPoints <= 0){
        healthPoints = 40;
    }
    
}
void hammer(){
    
}

void trapAction(){
    
    int computerNumber = rand() % 9 + 1;
    int trials = 3;
    int playerGuess = -1;
    cin >> playerGuess;
    
    while(trials > 1 && playerGuess != computerNumber){
        
        cout << "Try again." << endl;
        cin >> playerGuess;
        
        while(!cin)
        {
            // user didn't input a number
            cin.clear(); // reset failbit
            cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); //skip bad input
            // next, request user reinput
            cout << "Enter a number." << endl;
            cin >> playerGuess;
        }
        
        //Check if input is in the range.
        while(playerGuess < 1 || playerGuess > 9){
            cout << "Enter a valid value." << endl;
            cin >> playerGuess;
        }
        
        trials--;
            
        
//        if(playerGuess == computerNumber){
//            cout << "You suddenly notice the suspicious trap on the floor and dodge it." << endl;
//            break;
//        }
        
    }
    if(playerGuess != computerNumber){
        healthPoints -= 10;
    }
    else{
        cout << "You suddenly notice the suspicious trap on the floor and dodge it." << endl;
    }
    
}

void monsterAction(){
    int computerChoice = rand() % 3 + 1;
    int playerGuess = 0;
    cin >> playerGuess;
    
    while(!cin) // or if(cin.fail())
    {
        // user didn't input a number
        cin.clear(); // reset failbit
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); //skip bad input
        // next, request user reinput
        cout << "Enter a number." << endl;
        cin >> playerGuess;
    }
    //Check if input is in the range.
    while(playerGuess < 1 || playerGuess > 3){
        cout << "Enter a valid value." << endl;
        cin >> playerGuess;
    }
    
    if(playerGuess == 1 && computerChoice == 3){
        cout << "Monster attacks with scissors" << endl;
        cout << "The monster is stunned, run!" << endl;
    }
    else if(playerGuess == 2 && computerChoice == 1){
        cout << "Monster attacks with rock" << endl;
        cout << "The monster is stunned, run!" << endl;
    }
    else if(playerGuess == 3 && computerChoice == 2){
        cout << "Monster attacks with paper" << endl;
        cout << "The monster is stunned, run!" << endl;
    }
    else{
        cout << "The monster attacked you by surprise, you're hurt. Run away!" << endl;
        healthPoints -= 30;
    }
    
}




