#include <iostream>
#include <string>
#include <iomanip>
#include <cstdlib>
#include <ctime>
#include "graphicFcts.h"


using namespace std;

//Array to draw.
const int row = 20;
const int col = 20;
string room[col][row];

//Stores current position of player.
int currentRow = 1;
int currentCol = 1;

//Stores input from user for movement (W,A,S,D).
string movement = "X";

//Stores position of traps and monsters.
int randomTrapGeneratorRow;
int randomTrapGeneratorCol;
int randomMonsterGeneratorRow;
int randomMonsterGeneratorCol;

//Stores position of items.
int gogglesRow;
int gogglesCol;
int potionRow;
int potionCol;
int hammerCol;
int hammerRow;

//Tracks state of inventory.
bool gogglesFound = false;
bool potionFound = false;
bool hammerFound = false;

//State of traps depending on position of user.
bool nearbyTrap = false;

//Tracks if user is allowed second attack with hammer.
bool secondAttackOccurred = false;

//Keeps track of state of game.
bool gameWon = false;
bool dead = false;
bool validMove = true;
bool startOfGame = true;

//Keeps track of state of player.
bool hitTrap = false;
bool hitMonster = false;

//Keeps track when trap and monster positions change.
int changeTraps = 0;

int healthPoints = 100;


//Print instructions at the beginning.
void printInstructions(){
    
    string input;
    cout << setw(110) << "D U N G E O N  M A S T E R \n" << endl;
    cout << "\n" << "\t\t\t\t\tWelcome to Dungeon Master. Your goal is to reach the bottom right corner to escape the dungeon." << endl;
    cout << "\n" << "\t\t\t\t\tIf you meet a trap, you will have 3 chances to find the random number from 0 to 9 generated by the dungeon and lose 15HP." << endl;
    cout << "\t\t\t\t\tIf you meet a monster, you'll have to play a rock-paper-scissors game and lose 30HP. " << endl;
        
    cout << "\n" << "\t\t\t\t\tThe Master is playful. He changes the trap positions often and monsters move fast. Take that into consideration." << endl;
    
    cout << "\n" << "\t\t\t\t\t\t\t\tThis is your character: ᗤ. Move using W, S, A, D." << endl;
    
    cout << "\n" << "\t\t\t\t\tYou might encouter different items during the game: " << endl;
    cout << "\t\t\t\t\t\t♥ - The Potion of Ressurection. If you die, it will ressurect you with 40 HP." << endl;
    cout << "\t\t\t\t\t\t⎌ - The Master's Goggles. If a trap is directly in front of you, it will signal you with the following symbol: ⚠︎." << endl;
    cout << "\t\t\t\t\t\t⚒︎ - The Thunder Hammer. You get an extra chance every time you face a monster." << endl;
    
    cout << "\n\n" << "\t\t\t\t\t\t\t\t\tPress any key when you're ready to start" << endl;
    cin >> input;
    if(input == "cheat"){
        gogglesFound = true;
        hammerFound = true;
        potionFound = true;
    }
    drawRoom();
    
    
}

//Draws board.
void drawRoom(){
    
   if(dead != true){
    bigSpace();
    }
    
    for (int i=0; i<row; i++){
        for (int j=0; j<col; j++){
            
            if(startOfGame == true){
                room[1][1] = "ᗧ";
            }
            
            //Draws player.
            if(i == currentRow && j == currentCol){
                
                if (movement == "A" || movement == "a") {
                    room[i][j] = "ᗤ";
                }
                
                else if(movement == "S" || movement == "s"){
                    room[i][j] = "ᗣ";
                    if(i == row - 2 && j == col - 2){
                        gameWon = true;
                    }
                }
                
                else if(movement == "W" || movement == "w"){
                    room[i][j] = "ᗢ";
                }
                
                else if (movement == "D" || movement == "d"){
                    room[i][j] = "ᗧ";
                }
                
                if(i == row - 2 && j == col - 2){
                    gameWon = true;
                }
                
            }
            
            
            //Draws room.
            else if(i == 0){
                room [i][j] = "-";
            }
            else if(j == col-1 && i < row - 2){
                room[i][j] = "|";
            }
            else if(i == row-1){
                room[i][j] = "-";
            }
            else if(j == 0){
                room[i][j] = "|";
            }
            else{
                room[i][j] = ".";
            }
            
            
            cout << room[i][j];
            
            //Prints parameters on the side of the screen.
            //i variables are the rows at which we print.
            if(j == col-1){
                //1. Print HP.
                if(i==1){
                    cout << "\t \t \t \t  HP: " << healthPoints;
                }
                
                //2. If goggles found, print inventory.
                if(gogglesFound == true){
                    if(i == 2){
                        cout << "\t \t \t \t  ITEM: ⎌";
                    }
                    //If next move makes player walk on trap, notify him.
                    if(randomMonsterGeneratorRow != 0 && randomTrapGeneratorCol != 0){
                        
                        if(((movement == "S" || movement == "s") && (currentRow+1) % randomTrapGeneratorRow == 0 && currentCol % randomTrapGeneratorCol == 0) ||
                           ((movement == "W" || movement == "w") && (currentRow-1) % randomTrapGeneratorRow == 0 && currentCol % randomTrapGeneratorCol == 0) ||
                           ((movement == "D" || movement == "d") && (currentRow) % randomTrapGeneratorRow == 0 && (currentCol+1) % randomTrapGeneratorCol == 0) ||
                           ((movement == "A" || movement == "a") && (currentRow) % randomTrapGeneratorRow == 0 && (currentCol-1) % randomTrapGeneratorCol == 0)){
                            if(i == 5){
                                cout <<"\t \t \t \t  DANGER: ⚠︎";
                            }
                        }
                    }
                }
                
                //3. If potion found, print inventory.
                if(potionFound == true){
                    if (i == 3){
                        cout << "\t \t \t \t  ITEM: ♥";
                    }
                }
                
                //3. If hammer found, print inventory.
                if(hammerFound == true){
                    if(i == 4){
                        cout << "\t \t \t \t  ITEM: ⚒︎";
                    }
                }
                
                
                //If user hits a trap, invite to play.
                if(hitTrap == true){
                    if(i == 10){
                        cout << "\t \tTrap! Guess the number in 0-9.";
                    }
                }
                
                //If user encounters a monster, invite to play.
                else if(hitMonster == true){
                    if(i == 10){
                        cout << "\t \tMonster! Rock (1), paper (2) or scissors (3)?";
                    }
                }
                
                //Simple note at the bottom for information purposes.
                if(i == 13){
                    cout << "\t\tNote: traps trigger when foot is taken off...";
                }
                
            }
            
            //If player wins the game, print & exit.
            if(gameWon == true){
                endBox(dead);
                cout << "\n\nGAME WON!" << endl;
                exit(0);
            }
            //If player dies, print & exit.
            if(dead == true){
                
                endBox(dead);
                exit(0);
            }
            
            
        }
        
        cout << "\n";
        
    }
    
    //Figthing actions.
    if(hitTrap == true){
        trapAction();
        //Delete previous key stroke to avoid weird behavior.
        cin.clear();
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        cin.sync();
    }
    if(hitMonster == true){
        monsterAction();
    }
    
    
    
}

//Adjust the currentRow & currentCol variables so that position is changed when drawRoom() is executed.
void drawPlayer(){
    
    //Initializes first position to top left corner.
    if(startOfGame == true){
        currentRow = 1;
        currentCol = 1;
        startOfGame = false;
    }
    
    //If HP <= 0, check if user has potion. If yes, resurrect him. If not, dead = true will end the game.
    if(healthPoints <= 0){
        if(potionFound == false){
            dead = true;
        }
        else if(potionFound == true){
            potion();
            potionFound = false;
        }
    }
    
    else{
        
        cin.sync();
        cin >> movement;
        cin.ignore();
        
        //Only keep first character of whatever user inputs.
        movement = movement.substr(0, 1);
        
        if(movement == "S" || movement == "s"){
            currentRow = currentRow + 1;
            if(currentRow < row - 1){
                validMove = true;
            }
            else{
                validMove = false;
                currentRow = currentRow - 1;
            }
        }
        else if(movement == "W" || movement == "w"){
            currentRow = currentRow - 1;
            if(currentRow > 0){
                validMove = true;
            }
            else{
                validMove = false;
                currentRow = currentRow + 1;
            }
        }
        else if(movement == "D" || movement == "d"){
            currentCol = currentCol + 1;
            if(currentCol < col - 1){
                validMove = true;
            }
            else{
                validMove = false;
                currentCol = currentCol - 1;
            }
        }
        else if(movement == "A" || movement == "a"){
            currentCol = currentCol - 1;
            if(currentCol > 0){
                validMove = true;
            }
            else{
                validMove = false;
                currentCol = currentCol +1;
            }
        }
        
    }
    
    room[currentCol][currentRow] = "ᗤ";
    

    if(validMove == true){
        drawRoom();
    }
    
}

//Function to generate the positions of the traps and monsters. It also checks of user stepped/encoutered one.
void checkTrap(){
    
    //Seed our random number generator.
    srand(time(NULL));
    
    //Change position of traps every 5 movements, if the user was hit by a monster or trap, or if it's the beginning of the game.
    if(changeTraps % 5 == 0 || hitTrap == true || hitMonster == true || startOfGame == true){
        hitMonster = false;
        hitTrap = false;
        nearbyTrap = false;
        
        //1/5 is a factor I found appropriate for the frequency of traps and monsters on the board.
        randomTrapGeneratorRow = rand() % (row/5 - 1) + 2;
        randomTrapGeneratorCol = rand() % (col/5 - 1) + 2;
        randomMonsterGeneratorRow = rand() % (row/5 - 1) + 2;
        randomMonsterGeneratorCol = rand() % (col/5 - 1) + 2;
    }
   
//    cout << "TRAP R " << randomTrapGeneratorRow << " C " << randomTrapGeneratorCol << endl;
//    cout << "ME R " << currentRow << " C " << currentCol << endl;
    
    if (currentRow % randomTrapGeneratorRow == 0 && currentCol % randomTrapGeneratorCol == 0){
        hitTrap = true;
    }
    else if(currentRow % randomMonsterGeneratorRow == 0 && currentCol % randomMonsterGeneratorCol == 0){
        hitMonster = true;
    }
    
    changeTraps++;
    
}

//Function to check if player found a special item.
void checkItem(){
    
    if(currentRow == gogglesRow && currentCol == gogglesCol){
        gogglesFound = true;
    }
    else if(currentRow == potionRow && currentCol == gogglesCol){
        potionFound = true;
    }
    else if(currentRow == hammerRow && currentCol == hammerCol){
        hammerFound = true;
    }
    
}

//Function to randomly generate position of items. Factor 1/2 is used to put the items in the upper half of the board.
void generateItems(){
    
    srand(time(NULL));
    
    gogglesRow = rand() % (row/2) + 1;
    gogglesCol = rand() % (col/2) + 1;
    potionRow = rand() % (row/2)+ 1;
    potionCol = rand() % (col/2) + 1;
    hammerRow = rand() % (row/2) + 1;
    hammerCol = rand() % (col/2) + 1;
    
    
}

//Function that simulates the potion action.
void potion(){
    if(potionFound == true && healthPoints <= 0){
        healthPoints = 40;
    }
    
}

//Function that simulates what happens when user finds a trap.
void trapAction(){
    
    beepSound();
    int computerNumber = rand() % 9 + 1;
    int trials = 3;
    int playerGuess = -1;
    cin >> playerGuess;
    
    //Check if user inputs a number.
    while(!cin)
    {
        // user didn't input a number
        cin.clear(); // reset failbit
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); //skip bad input
        // next, request user reinput
        cout << "Enter a number." << endl;
        cin >> playerGuess;
    }
    //Check if input is in the range.
    while(playerGuess < 0 || playerGuess > 9){
        cout << "Enter a valid value." << endl;
        cin >> playerGuess;
    }
    
    //Play the game and give the player 3 chances.
    while(trials > 1 && playerGuess != computerNumber){
        
        cout << "Try again." << endl;
        cin >> playerGuess;
        
        while(!cin)
        {
            // user didn't input a number
            cin.clear(); // reset failbit
            cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); //skip bad input
            // next, request user reinput
            cout << "Enter a number." << endl;
            cin >> playerGuess;
        }
        
        //Check if input is in the range.
        while(playerGuess < 0 || playerGuess > 9){
            cout << "Enter a valid value." << endl;
            cin >> playerGuess;
        }
        
        trials--;
        
        
    }
    
    if(playerGuess != computerNumber){
        cout << "OUCH, you are hit by a hidden trap! Keep moving!" << endl;
        healthPoints -= 15;
    }
    else{
        cout << "You suddenly notice the suspicious trap on the floor and dodge it." << endl;
    }
    
    
}

//Function that simulates what happens when player encounters a monster.
void monsterAction(){
    
    beepSound();
    int computerChoice = rand() % 3 + 1;
    int playerGuess = 0;
    secondAttackOccurred = false;
    
    while(true){
        cin >> playerGuess;
        
        //Check if input is number.
        while(!cin) // or if(cin.fail())
        {
            // user didn't input a number
            cin.clear(); // reset failbit
            cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); //skip bad input
            // next, request user reinput
            cout << "Enter a number." << endl;
            cin >> playerGuess;
        }
        //Check if input is in the range.
        while(playerGuess < 1 || playerGuess > 3){
            cout << "Enter a valid value." << endl;
            cin >> playerGuess;
        }
        
        
        //Different cases in the game.
        //1. Cases when user wins.
        if(playerGuess == 1 && computerChoice == 3){
            cout << "Monster attacks with scissors" << endl;
            cout << "The monster is stunned, run!" << endl;
            break;
        }
        
        else if(playerGuess == 2 && computerChoice == 1){
            cout << "Monster attacks with rock" << endl;
            cout << "The monster is stunned, run!" << endl;
            break;
        }
        
        else if(playerGuess == 3 && computerChoice == 2){
            cout << "Monster attacks with paper" << endl;
            cout << "The monster is stunned, run!" << endl;
            break;
        }
        
        //2. Cases when user loses.
        else{
            //Check if user has hammer. If yes => second chance.
            if(hammerFound == false){
                cout << "The monster attacked you by surprise, you're hurt. Run away!" << endl;
                healthPoints -= 30;
                break;
            }
            //If hammer, check if user already used his second chance.
            else if(hammerFound == true){
                if(secondAttackOccurred == false){
                    cout << "You're able to hit the monster again with your hammer. Rock, paper, or scissors?" << endl;
                    secondAttackOccurred = true;
                    continue;
                }
                else{
                    cout << "The monster attacked you by surprise, you're hurt. Run away!" << endl;
                    healthPoints -= 30;
                    break;
                }
            }
        }
        
        
    }
    
    
}

void endBox(bool death){
    cout << "\n\n";
    string box[5][10];
    cout << "\n";
    for(int i=0; i<5; i++){
        for(int j=0; j<10; j++){
            if(i==0 || i==4){
                box[i][j] = "-";
            }
            else if(j==0 || j==9){
                box[i][j] = "|";
            }
            else if(i == 1 && j == 3){
                box[i][j] = "G";
            }
            else if(i == 1 && j == 4){
                box[i][j] = "A";
            }else if(i == 1 && j == 5){
                box[i][j] = "M";
            }else if(i == 1 && j == 6){
                box[i][j] = "E";
            }
            else if(i == 3 && j == 3){
                if(death == true){
                    box[i][j] = "O";
                }
                else{
                    box[i][j] = "W";
                }
            }
            else if(i == 3 && j == 4){
                if(death == true){
                    box[i][j] = "V";
                }
                else{
                    box[i][j] = "O";
                }
            }
            else if(i == 3 && j == 5){
                if(death == true){
                    box[i][j] = "E";
                }
                else{
                    box[i][j] = "N";
                }
            }else if(i == 3 && j == 6){
                if(death == true){
                    box[i][j] = "R";
                }
                else{
                    box[i][j] = "!";
                }
            }
            
            else{
                box[i][j] = " ";
            }
            
            cout << box[i][j];
        }
        cout << "\n";
    }
    cout << "\n\n\n";
}


void bigSpace(){
    cout << "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
}

void beepSound(){
    cout << '\a';
}




